theme: jekyll-theme-dinky
title: Africa Rising is here
description: A rapid description of the website content
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'What is #africarising?', 'pagename': 'Introduction'},
{'name': 'Data colelction', 'pagename': 'Methodology'},
{'name': 'Global Analysis', 'pagename': 'tweets'},
{'name': 'Regional Analysis', 'pagename': 'FDI'},
{'name': 'Conclusion', 'pagename': 'Conclusion'},
]
